config/routes.rb
Rails.application.routes.draw do
  root "words#home"
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'callbacks' }
  resources :words, only: [:index, :home, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews do
      resources :votes, only: [:create]
    end
  end
  resources :users do
    member do
      patch :favorite_word
      patch :remove_favorite
      delete :remove_avatar
    end
  end
  resources :search, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :words
  has_many :reviews
  has_many :votes

  validates_uniqueness_of :username
  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github, :facebook]

  def self.from_omniauth(auth)
    if User.where(email: auth.info.email)[0]
      User.where(email: auth.info.email)[0]
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.username = auth.info.nickname if auth.provider == 'github'
        user.username = auth.info.name if auth.provider == 'facebook'
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.try(:admin?)
      @users = User.all.order(created_at: :asc)
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  def show
    @user = User.find(params[:id])
    @default_image = "Man_Silhouette.jpg"
    @votes = @user.votes.order(created_at: :desc).limit(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.avatar = params[:user][:avatar]
    user.save
    redirect_to user_path(user)
  end

  def favorite_word
    current_user.update(favorite_word_id: params[:word_id])
  end

  def remove_favorite
    current_user.update(favorite_word_id: nil)
  end

  def remove_avatar
    user = User.find(params[:id])
    user.remove_avatar!
    user.save
    redirect_to user_path(user)
  end

  def destroy
    @user = User.find(params[:id])
    if authorized_party
      if @user.valid?
        user_valid_destroy
      else
        flash[:errors] = "User Account was not closed"
        render user_path(@user)
      end
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  private

  def authorized_party
    current_user.try(:admin?) || current_user == @user
  end

  def admin_redirect
    if current_user.admin
      redirect_to users_path
    else
      redirect_to root_path
    end
  end

  def user_valid_destroy
    @user.reviews.each do |review|
      review.votes.destroy_all
      review.destroy
    end
    @user.words.each do |word|
      word.reviews.destroy_all
      word.destroy
    end
    @user.votes.destroy_all
    @user.destroy
    flash[:success] = "User Account successfully closed"
    admin_redirect
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br>
<div class="row">
  <div class="col s8">
    <%= form_for :user, method: :patch, url: user_path(@user) do |f| %>
      <div class="field">
        <h5>Choose a New Profile Picture</h5>
        <%= f.file_field :avatar %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Update Profile Picture", class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="row">
  <div class="col s12">
    <% if @user.avatar? %>
      <%= image_tag @user.avatar_url(:thumb) %>
    <% else %>
      <%= image_tag @default_image %>
    <% end %>
    <% if current_user == @user %>
      <%= link_to 'Update Profile Picture', edit_user_path(@user), class: "btn" %>
    <% end %>
    <% if current_user == @user  && @user.avatar? %>
      <%= link_to "Delete Profile Picture", remove_avatar_user_path(@user), method: :delete, class: "btn" %>
    <% end %>
    <h1><%= @user.username %>'s Profile Page</h1>
  </div>

  <div class="col s12">
    <% if @user.favorite_word_id %>
      <h5 id="fav_word">Favorite Word: <%= Word.find(@user.favorite_word_id).word %></h5>
      <% if current_user == @user %>
        <%= link_to "Remove Favorite Word", remove_favorite_user_path, method: :patch, class: "btn" %>
      <% end %>
    <% end %>
    <br><br><hr><br>
  </div>

  <h2>Submitted Words</h2>
  <% @user.words.each do |word| %>
    <ul>
      <li>
        <%= link_to word.word, word_path(word), id: "word#{word.id}" %>
        <% if current_user == @user %>
          <%= link_to "Update #{word.word}", edit_word_path(word), class: "btn" %>
        <% end %>
      </li>
    </ul>
  <% end %>

  <div id="last_five_votes">
    <div class="col s8">
      <h2>Five Most Recent Votes</h2>
      <hr>
      <% @votes.each_with_index do |vote, index|  %>
      <div class="col s12">
        <%= index + 1 %>.)
        Word: <%= link_to vote.review.word.word, word_path(vote.review.word.id) %><br/>
        Review Text: <%= vote.review.body %><br/>
        <% if vote.up_down %>
        Vote: Upvoted!
        <% else %>
        Vote: Downvoted!
        <% end %>
        <br/><br/>
      </div>
      <hr>
      <% end %>
    </div>
  </div>

  <div class="col s8" id="submitted_reviews">
    <h2>Submitted Reviews</h2>
    <hr>
      <% @user.reviews.each do |review| %>
        <div class="col s12">
          <p>Reviewed Word: <%= link_to review.word.word, word_path(review.word.id)%><br/>
          Rating: <%= review.rating %><br/>
          Review: <%= review.body %></p>
        </div>
        <hr>
      <% end %>
  </div>

  <div class="col s8">
    <% if current_user.try(:admin?) || current_user == @user %>
      <%= link_to "Edit your account", edit_user_registration_path, class: "btn" %>
      <%= link_to "Delete User Account", user_path(@user), method: :delete, class: "btn" %>
    <% end %>
  </div>
</div>