config/routes.rb
Rails.application.routes.draw do
  root "words#home"
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'callbacks' }
  resources :words, only: [:index, :home, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews do
      resources :votes, only: [:create]
    end
  end
  resources :users do
    member do
      patch :favorite_word
      patch :remove_favorite
      delete :remove_avatar
    end
  end
  resources :search, only: [:index]
end

app/models/word.rb
class Word < ApplicationRecord
  max_paginates_per 20
  belongs_to :user
  has_many :reviews

  validates :word, presence: true, allow_blank: false
  validates :definition, presence: true, allow_blank: false
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :fetch_word, only: [:show, :edit, :update, :destroy]

  def index
    @words = Word.all.order!(created_at: :desc).page params[:page]
    respond_to do |format|
      format.html
      format.json do
        response_array = []
        @words.each do |word|
          response_array << { id: word.id, word: word.word }
        end
        render json: response_array.to_json
      end
    end
  end

  def home
    @words = Word.all.order(created_at: :desc).limit(10)
  end

  def show
    @review = Review.new
    @reviews = @word.reviews
    @default_image = "Man_Silhouette.jpg"
  end

  def new
    if current_user
      @word = Word.new
    else
      flash[:errors] = "You must be logged in to create a word."
      redirect_to root_path
    end
  end

  def create
    if current_user
      @word = Word.new(word_params)
      if @word.save
        flash[:success] = "Word up!"
        redirect_to root_path
      else
        flash[:errors] = "Word could not be created."
        render :new
      end
    end
  end

  def edit
  end

  def update
    @word.definition = params[:word][:definition]
    if authorized_party
      if @word.save
        flash[:success] = "Word was Updated!"
        redirect_to word_path(@word)
      else
        flash[:error] = "Word could not be Updated"
        render word_path(@word)
      end
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  def destroy
    if authorized_party
      if @word.valid?
        @word.reviews.destroy_all
        @word.destroy
        flash[:success] = "Word was deleted!"
        redirect_to words_path
      else
        flash[:error] = "Word could not be deleted"
        render word_path(@word)
      end
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  private

  def word_params
    params.require(:word).permit(:word, :definition).merge(user: current_user)
  end

  def fetch_word
    @word = Word.find(params[:id])
  end

  def authorized_party
    current_user.try(:admin?) || current_user == @word.user
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/edit.html.erb
<div class="row">
  <div class="col s8">
    <h2><%= @word.word %></h2>
  </div>
  <div class="col s8">
    <%= form_for :word, method: :patch, url: word_path(@word) do |f| %>

      <%= f.label :definition, class: "new_word_label" %>
      <%= f.text_area :definition, class: "text_area" %>

      <%= f.submit "Update Word", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/words/home.html.erb
<div class="row">
  <div class="col s8">
    <h1>10 Most Recent Words</h1>
  </div>
  <div class="col s8" id="word_list">
    <% @words.each do |word| %>
      <li><%= link_to word.word, word_path(word.id) %></li>
    <% end %>
  </div>
</div>

app/views/words/index.html.erb
<div id="flash_bar" class="row">
  <% if flash[:error] %>
    <h5 class="center-align"><%= flash[:error] %></h5>
  <% end %>
</div>

<h1>All Words on WordUp</h1>

<div id="app">
</div>
<div id="index_div">
  <% @words.each do |word| %>
    <li><%= link_to word.word, word_path(word.id) %></li>
  <% end %>
</div>
<div>
  <%= paginate @words %>
</div>

app/views/words/new.html.erb
<h1>Add a new word</h1>
<% if flash[:errors] %>
  <p>
    <%= flash[:errors] %>
  </p>
<% end %>
<%= form_for :word, url: words_path do |f| %>
  <div class="row">
    <div class="col s8">
      <%= f.label :word, class: "new_word_label" %>
      <%= f.text_field :word %>
    </div>
  </div>

  <div class="row">
    <div class="col s8">
      <%= f.label :definition, class: "new_word_label" %>
      <%= f.text_area :definition, class: "text_area" %>
    </div>
  </div>

  <div class="row">
    <div class="col s8">
      <%= f.submit "Create Word", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/words/show.html.erb
<br/>
<div class="row">
  <div class="col s8">
    <h2 class="word_head"><%= @word.word %></h2>
    <% if current_user %>
      <% if current_user.favorite_word_id == @word.id %>
        <button class="btn" id="fav_button" onClick="unfavorite(null, <%= @word.id %>, <%= current_user.id %>)">Unfavorite Word</button>
        <% favorited = "Favorited" %>
      <% else %>
        <button class="btn" id="fav_button" onClick="favorite(null, <%= @word.id %>, <%= current_user.id %>)">Favorite Word</button>
        <% favorited = "" %>
      <% end %>
    <% end %>
    <div id="fav_word"><%= favorited %></div>
  </div>
  <div class="col s8">
    <h3 class="word_def">Defintion:</h3>
    <% if current_user.try(:admin?) || current_user == @word.user %>
      <%= link_to 'Update Content', edit_word_path(@word), class: "btn" %>
    <% end %>
    <p><%= @word.definition %></p>
  </div>
  <div class="col s8" id="word_user">
    <h5 class="creator_tag">
      <% if @word.user.avatar? %>
        <%= image_tag @word.user.avatar_url(:thumb) %>
      <% else %>
        <%= image_tag @default_image %>
      <% end %>
      Submitted by: <%= link_to @word.user.username, user_path(@word.user) %>
    </h5>
    <br/><br/><hr>
  </div>
  <div class="col s8">
    <h4>Reviews</h4>
      <% @reviews.each do |review| %>
        <hr><br>
        <div id="review_user<%= review.id %>">
          <p class="creator_tag">
            <% if review.user.avatar? %>
              <%= image_tag review.user.avatar_url(:thumb) %>
            <% else %>
              <%= image_tag @default_image %>
            <% end %>
            Submitted by: <%= link_to review.user.username, user_path(review.user) %>
          </p>
        </div>
        <h4>Rating: <%= review.rating %>/5</h4>
        <p><%= review.body %></p>
        <% if current_user %>
          <% if !current_user.votes.empty? %>
            <% if current_user.votes.find_by(review_id: review.id) %>
              <% if current_user.votes.find_by(review_id: review.id).up_down %>
                <% up_button_class_name = "upvoted" %>
              <% else %>
                <% down_button_class_name = "downvoted" %>
              <% end %>
            <% end %>
          <% end %>
          <button id="up<%= review.id %>" class="btn <%= up_button_class_name %>" onClick="vote(true, <%= @word.id %>, <%= review.id %>)">Up</button>
          <button id="down<%= review.id %>" class="btn <%= down_button_class_name %>" onClick="vote(false, <%= @word.id %>, <%= review.id %>)">Down</button>
        <% end %>
        <div class="review_score" id="count<%= review.id %>">
          Review Score: <%= review.votes.where(review_id: review.id, up_down: "true").count - review.votes.where(review_id: review.id, up_down: "false").count %>
        </div>
        <br><br>
        <div>
          <% if current_user.try(:admin?) || current_user == review.user %>
          <%= link_to "Edit Review", edit_word_review_path(@word, review), class: "btn" %>
          <%= link_to "Delete Review", word_review_path(@word, review), method: :delete, class: "btn" %>
          <% end %>
        </div>
        <br>
      <% end %>
      <hr>
    <% if user_signed_in? %>
      <h4>Write a new review for <%= @word.word %></h4>
      <%= render "/layouts/review_form" %>
    <% end %>
  </div>
</div>
<br/>
<br/>
<div class="row">
  <div class="col s8">
    <div class="row">
      <div class="col s8">
        <% if current_user.try(:admin?) || current_user == @word.user %>
          <%= link_to "Delete Word",  word_path(@word), method: :delete, class: "btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>