config/routes.rb
Rails.application.routes.draw do
  root "words#home"
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'callbacks' }
  resources :words, only: [:index, :home, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews do
      resources :votes, only: [:create]
    end
  end
  resources :users do
    member do
      patch :favorite_word
      patch :remove_favorite
      delete :remove_avatar
    end
  end
  resources :search, only: [:index]
end

app/views/layouts/_edit_review_form.html.erb
<%= form_for [@word, @review] do |f| %>
  <%= f.label :rating, "Rating" %>
  <%= f.select :rating, options_for_select(["0", "1", "2", "3", "4", "5"]) %>

  <%= f.label :review, "Edit Review" %>
  <%= f.text_field :review %>

  <%= f.submit "Save Changes" %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= form_for [@word, @review] do |f| %>
  <div class='row'>
      <% unless @review.user && current_user.try(:admin?)%>
      <div class='col s8'>
        <%= f.label :rating, "Rating", class: "new_word_label" %>
        <%= f.select :rating, options_for_select(["0", "1", "2", "3", "4", "5"]), {}, { class: 'browser-default' } %>
      </div>
      <% end %>

    <div class='col s8'>
      <%= f.label :body, "Review Text", class: "new_word_label" %>
      <%= f.text_area :body, class: "text_area" %>
    </div>

    <div class='col s8'>
      <%= f.submit "Save Review",class: "btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/_sign_in_form.html.erb
<%= form_for(:user, url: session_path(:user)) do |f| %>
  <div class='row right col s12 m6 l6'>
    <div class='col s6 m4 l3'>
      <%= f.label :email, "Login-Email", class: "search_label" %>
      <%= f.text_field :email, class: "search_text" %>
    </div>
    <div class='col s6 m4 l3'>
      <%= f.label :password, "Login-Password", class: "search_label" %>
      <%= f.password_field :password, class: "search_text" %>
    </div>
    <div class='col s6 m4 l3'>
      <br/>
      <%= f.submit "Sign in", id: "login_btn", class: 'btn' %>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
    <div class="col s4 l3 forgot">
      <%= link_to "Forgot your password?", new_user_password_path(:user), id: "top_link" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlyLikeAG9</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=ABeeZee|Bangers|Chewy|Covered+By+Your+Grace|Maven+Pro|Permanent+Marker|Rock+Salt|Special+Elite" rel="stylesheet">
  </head>

  <body>
    <div id="topmost_bar" class="row valign">
      <div class='col s12 m6 l6 left'>
        <%= form_tag search_index_path, method: 'get' do %>
          <div class="col s8">
            <%= label_tag :search, "Search for a word:", class: "search_label" %>
            <%= text_field_tag :search, params[:search], class: "search_text" %>
          </div>
          <br/>
          <div class="col s2">
            <%= submit_tag "Search", name: nil, class: 'btn' %>
          </div>
        <% end %>
      </div>
        <% if current_user %>
            <div class="col s6 right">
              <br/>
              <h5 id="nav_info"><span>Signed in as <%= current_user.username %></span> /
              <span><%= link_to "My Profile", user_path(current_user) %></span> /
              <span><%= link_to "Logout", destroy_user_session_path, method: :delete %></span></h5>
            </div>
        <% else%>
          <% if controller_name != "sessions" && action_name != "new" %>
            <% if controller_name != "registrations"%>
              <% if action_name != "new" || action_name != "show" %>
                <div class='row valign'>
                  <%= render "layouts/sign_in_form" %>
                </div>
              </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <% if !current_user %>
        <div id="sub_top_bar" class='row'>
          <div class='col right'>
            <%= link_to "Github", user_github_omniauth_authorize_path, id: "top_link", class: "sign_in_links" %>
            <%= link_to "Facebook", user_facebook_omniauth_authorize_path, id: "top_link", class: "sign_in_links"  %>
            <%= link_to "Sign up", new_user_registration_path, id: "top_link", class: "sign_in_links"  %>
          </div>
        </div>
      <% end %>

      <div id="bread_bar" class='row valign'>
        <div id="Moop" class='nav_btn btn header-link'><%= link_to "Home", root_path %></div>
        <div class='nav_btn btn header-link'><%= link_to "All Words", words_path %></div>
        <div class='nav_btn btn header-link'><%= link_to "Add a new word", new_word_path %></div>
      </div>

      <div id="flash_bar" class="row">
        <% if flash[:notice] %>
          <h5 class="center-align"><%= flash[:notice] %></h5>
        <% end %>
        <% if flash[:success] %>
          <h5 class="center-align"><%= flash[:success] %></h5>
        <% end %>
        <% if flash[:errors] %>
          <h5 class="center-align"><%= flash[:errors] %></h5>
        <% end %>
      </div>
    <%= yield %>
  </body>
</html>